sites: "" # Add the website here, that you want to be notified on
access_token: "" # Enter Pushbullet Access Token
devices:
    - [""] # Use the --list-devices argument and --add-device.
           # If done manually, separate each site by comma, do not remove the [].
